# Generated by Django 4.2.7 on 2023-12-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_blogpost_id_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='имя контакта'),
        ),
    ]
